"""The screenplay. Each scene: list of beats. Durations come from the TTS audio."""

VOICES = {
    'anchor': dict(voice='am_michael', speed=1.08, pitch=1.0),
    'narrator': dict(voice='bm_george', speed=0.95, pitch=1.0),
    'kevin': dict(voice='am_puck', speed=1.12, pitch=1.06),
    'parrot': dict(voice='af_sky', speed=1.06, pitch=1.18),
}

# beat types:
#   ('say', who, text, {opts})   opts: gap (pause after, s), tts (override spoken text), mark
#   ('pause', seconds)
#   ('sfx', name, {'at': offset from beat time, 'gain': g})
#   ('mark', name)
SCENES = [
    ('news', [
        ('pause', 0.5),
        ('say', 'anchor', "Breaking news. Experts confirm: A.I. has officially hit a wall.",
         {'tts': "Breaking news! Experts confirm: A I has officially hit a wall.", 'gap': 0.2}),
        ('say', 'anchor', "For the fifth year in a row.", {'gap': 0.3}),
        ('mark', 'wall_drop'), ('sfx', 'whoosh', {'at': -0.1}), ('sfx', 'thud', {'at': 0.35, 'gain': 1.4}),
        ('pause', 1.3),
        ('mark', 'crash'), ('sfx', 'rise', {'at': -1.0, 'gain': 0.5}), ('sfx', 'crash', {'gain': 1.2}),
        ('sfx', 'squawk', {'at': 0.2}),
        ('pause', 1.1),
        ('mark', 'title'), ('sfx', 'stamp', {'gain': 1.3}), ('sfx', 'stamp', {'at': 0.35, 'gain': 1.3}),
        ('pause', 1.7),
    ]),
    ('doc', [
        ('pause', 0.3),
        ('say', 'narrator', "Here, in the wild comment section, we find the common Skeptic.", {'gap': 0.15}),
        ('say', 'narrator', "Listen closely for its mating call.", {'gap': 0.25}),
        ('sfx', 'type', {}),
        ('say', 'kevin', "It's just a stochastic parrot. Fancy autocomplete, bro.", {'gap': 0.25}),
        ('sfx', 'squawk', {}),
        ('pause', 0.35),
        ('say', 'parrot', "Squawk! I'm literally right here, Kevin.", {'gap': 0.2}),
        ('say', 'narrator', "Let's test that theory.", {'gap': 0.3}),
        ('sfx', 'whoosh', {}),
    ]),
    ('round', {
        'n': 1, 'label': 'EXHIBIT A', 'colors': ('#4f7cff', '#3a63e0'),
        'icon': 'medal', 'big': 'GOLD', 'head': 'International Math Olympiad 2025',
        'lines': ['5 of 6 problems • 35/42 points', 'Written proofs, 4.5-hour time limit', 'Only 67 of 630 humans got gold'],
        'foot': 'Google DeepMind (officially graded) & OpenAI',
    }, [
        ('pause', 0.2), ('mark', 'card'), ('sfx', 'stamp', {'at': 0.1}),
        ('pause', 0.4),
        ('say', 'parrot', "Gold medal at the International Math Olympiad. Full written proofs.", {'gap': 0.25}),
        ('say', 'kevin', "Pfft. That's high school math.", {'gap': 0.15, 'mark': 'move'}),
        ('sfx', 'slide_up', {'at': 0.0}),
        ('pause', 0.55),
    ]),
    ('round', {
        'n': 2, 'label': 'EXHIBIT B', 'colors': ('#ff6b4a', '#e8553a'),
        'icon': 'code', 'big': '12 / 12', 'head': 'ICPC World Programming Finals 2025',
        'lines': ['Every problem solved', 'No human team got all 12', '139 university teams competed'],
        'foot': 'OpenAI (AI track). Gemini got 10/12, incl. one no human team solved.',
    }, [
        ('pause', 0.2), ('mark', 'card'), ('sfx', 'stamp', {'at': 0.1}),
        ('pause', 0.4),
        ('say', 'parrot', "World programming finals. Twelve out of twelve. No human team did that.", {'gap': 0.25}),
        ('say', 'kevin', "Contests aren't REAL coding.", {'gap': 0.15, 'mark': 'move',
                                                          'tts': "Contests aren't REAL coding."}),
        ('sfx', 'slide_up', {}),
        ('pause', 0.55),
    ]),
    ('round', {
        'n': 3, 'label': 'EXHIBIT C', 'colors': ('#18b88a', '#12a077'),
        'icon': 'agents', 'big': '100,000 LINES', 'head': 'A C compiler, written by 16 AI agents',
        'lines': ["About 2 weeks. Humans didn't write the code", 'Compiles a Linux kernel that boots',
                  'Agent task length: doubling every ~4-7 months'],
        'foot': 'Anthropic, Feb 2026 • METR time-horizon studies',
    }, [
        ('pause', 0.2), ('mark', 'card'), ('sfx', 'stamp', {'at': 0.1}),
        ('pause', 0.4),
        ('say', 'parrot', "Sixteen A.I. agents built a hundred-thousand-line C compiler. It compiles Linux.",
         {'gap': 0.25, 'tts': "Sixteen A I agents built a hundred thousand line C compiler. It compiles Linux."}),
        ('say', 'kevin', "Okay, but it can't discover anything NEW.", {'gap': 0.15, 'mark': 'move'}),
        ('sfx', 'slide_up', {}),
        ('pause', 0.55),
    ]),
    ('round', {
        'n': 4, 'label': 'EXHIBIT D', 'colors': ('#a55eea', '#8e44d8'),
        'icon': 'dots', 'big': 'DISPROVED', 'head': "Erdős's unit-distance conjecture (1946)",
        'lines': ['80-year-old conjecture, broken by an AI model', 'Checked by top mathematicians',
                  'Bonus: AlphaEvolve beat a 1969 matrix-math record'],
        'foot': 'OpenAI, May 2026 • Google DeepMind, 2025',
    }, [
        ('pause', 0.2), ('mark', 'card'), ('sfx', 'stamp', {'at': 0.1}),
        ('pause', 0.4),
        ('say', 'parrot', "Disproved an eighty-year-old Erdős conjecture. And broke a matrix math record from 1969.",
         {'gap': 0.25, 'tts': "Disproved an eighty year old Erdish conjecture. And broke a matrix math record from nineteen sixty nine."}),
        ('say', 'kevin', "It's just regurgitating its training data!", {'gap': 0.2, 'mark': 'move'}),
        ('sfx', 'slide_up', {}),
        ('pause', 0.3),
        ('say', 'parrot', "Regurgitating... an answer nobody had?", {'gap': 0.2, 'mark': 'q'}),
        ('mark', 'crickets'), ('sfx', 'scratch', {'at': -0.1}), ('sfx', 'cricket', {'at': 0.1}),
        ('pause', 1.5),
    ]),
    ('round', {
        'n': 5, 'label': 'EXHIBIT E', 'colors': ('#1e90ff', '#1878dd'),
        'icon': 'fluid', 'big': 'NAVIER–STOKES*', 'head': 'A $1M Millennium Prize problem',
        'lines': ['Lean-verified blow-up proof, forced version', '+ "100+ long-standing open problems"',
                  'in about a month (list not yet public)'],
        'foot': '*Claimed by OpenAI, Sept 2026. Experts still reviewing.',
    }, [
        ('pause', 0.2), ('mark', 'card'), ('sfx', 'stamp', {'at': 0.1}),
        ('pause', 0.4),
        ('say', 'parrot', "This month: a machine-checked Navier-Stokes blow-up proof. Plus a hundred more open problems.",
         {'gap': 0.2, 'tts': "This month: a machine checked Navier Stokes blow-up proof. Plus a hundred more open problems."}),
        ('say', 'narrator', "Claimed. Mathematicians are still checking. And arguing. Loudly.", {'gap': 0.2}),
        ('say', 'kevin', "Okay, but can it do SCIENCE science?", {'gap': 0.15, 'mark': 'move'}),
        ('sfx', 'slide_up', {}),
        ('pause', 0.55),
    ]),
    ('round', {
        'n': 6, 'label': 'EXHIBIT F', 'colors': ('#ff9f1a', '#f08a00'),
        'icon': 'flask', 'big': 'SCIENCE SCIENCE', 'head': 'Actual lab results',
        'lines': ['New antibiotics vs. superbugs (worked in mice)',
                  'AI-written virus genomes that actually work',
                  'Decade-long lab finding matched in 48 hours'],
        'foot': 'MIT 2025 • Arc Institute/Stanford 2025 • Google AI co-scientist 2025',
    }, [
        ('pause', 0.2), ('mark', 'card'), ('sfx', 'stamp', {'at': 0.1}),
        ('pause', 0.4),
        ('say', 'parrot', "New antibiotics for superbugs. Working virus genomes, written from scratch. A decade of lab work, matched in two days.",
         {'gap': 0.25}),
        ('say', 'kevin', "...Fine. But can it fold my laundry?", {'gap': 0.2, 'mark': 'move',
                                                                  'tts': "Fine. But can it fold my laundry?"}),
        ('sfx', 'slide_up', {}),
        ('pause', 0.2),
        ('say', 'parrot', "Kevin. You don't fold your laundry.", {'gap': 0.4}),
        ('sfx', 'boing', {'at': -0.35}),
    ]),
    ('space', [
        ('sfx', 'whoosh', {}),
        ('pause', 0.4),
        ('say', 'narrator', "The Skeptic's goalposts have now been spotted... in low Earth orbit.",
         {'gap': 0.5}),
        ('sfx', 'beep', {'at': -0.4}),
    ]),
    ('chart', [
        ('pause', 0.2),
        ('say', 'kevin', "Whatever. It's hit a wall.", {'gap': 0.3}),
        ('mark', 'chart'), ('sfx', 'whoosh', {}),
        ('say', 'narrator', "Ah yes. The wall. Here's how long a task A.I. agents can finish on their own.",
         {'gap': 0.1, 'mark': 'draw', 'tts': "Ah yes. The wall. Here's how long a task A I agents can finish on their own."}),
        ('pause', 2.4),
        ('say', 'parrot', "Which wall? We've smashed, like, five.", {'gap': 0.5}),
    ]),
    ('shop', [
        ('sfx', 'whoosh', {}),
        ('pause', 0.2),
        ('say', 'narrator', "Is it perfect? No. One A.I. ran an office snack shop at a loss...",
         {'gap': 0.1, 'tts': "Is it perfect? No. One A I ran an office snack shop at a loss."}),
        ('say', 'narrator', "and bought a pile of tungsten cubes.", {'gap': 0.3, 'mark': 'cubes'}),
        ('sfx', 'thud', {'at': -0.2}),
        ('say', 'parrot', "They were a great deal.", {'gap': 0.4}),
    ]),
    ('finale', [
        ('pause', 0.2),
        ('say', 'narrator', "But a parrot repeats. This thing proves.", {'gap': 0.4}),
        ('sfx', 'type', {}),
        ('say', 'kevin', "...stochastic parrot.", {'gap': 0.35, 'tts': "stochastic parrot."}),
        ('mark', 'shades'), ('sfx', 'rise', {'at': -0.8, 'gain': 0.5}),
        ('say', 'parrot', "Squawk. Polly want a Fields Medal.", {'gap': 0.2}),
        ('mark', 'endcard'), ('sfx', 'airhorn', {'gain': 0.9}), ('sfx', 'tada', {'at': 0.1, 'gain': 0.6}),
        ('pause', 3.6),
    ]),
]
